# my-mongo-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: primary
data:
  mongod.conf: |
    security:
      keyFile: /etc/key-file/keyfile.txt
    net:
      ssl:
        mode: allowSSL
        PEMKeyFile: /etc/key-file/mongodb.pem
        CAFile: /etc/key-file/root-ca.pem
        allowConnectionsWithoutCertificates: true
