apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "mongo-db"
  namespace: "rs-1"
spec:
  serviceName: "mongo-svc"
  replicas: 1
  selector:
    matchLabels:
      app: "mongo-db"
  template:
    metadata:
      labels:
        app: "mongo-db"
    spec:
      hostname: mongodb
      containers:
        - name: "mongo-db-rs"
          image: "mongo"
          imagePullPolicy: "Always"
          command:
            - mongod
            - bind_ip_all
            - --replSet
            - rs0
          ports:
            - containerPort: 27017
              name: "mongodb"
          volumeMounts:
            - name: "mongodb-persistent-storage-1"
              mountPath: "/data/db"
            - name: "mongo-config"
              mountPath: /etc/mongo
            - name: "replica-secrets"
              mountPath: /etc/key-file
      volumes:
        - name: "mongodb-persistent-storage"
          persistentVolumeClaim:
            claimName: "mongodb-pvc"
        - name: "mongo-config"
          configMap:
            name: "mongo-config"
        - name: "replica-secrets"
          secret:
            secretName: replica-secrets
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage-1
      spec:
        storageClassName: microk8s-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
