apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongo-svc"
  namespace: "rs-1"
  labels:
    app: "mongo-db"
spec:
  ports:
    - name: "mongodb"
      port: 27018
      targetPort: 27017
  clusterIP: "None"
  selector:
    app: "mongo-db"
